### ISSUE TITLE
get_activations not producing list

### ISSUE THREAD

**Issue by Toni-Antonova** [philipperemy/keras-attention-mechanism#1]
Thanks for uploading this to github! Great for learning more about attention models. When I run attention_dense.py, however, I get this error (after the model finishing training):

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-9-5fdd7f84f2d8> in <module>()
>      37     # Attention vector corresponds to the second matrix.
>      38     # The first one is the Inputs output.
> ---> 39     attention_vector = get_activations(m, testing_inputs_1, print_shape_only=True)[1].flatten()
>      40     print('attention =', attention_vector)
>      41 
> 
> IndexError: list index out of range

Any idea why the get_activations function isn't working properly?

**Comment by Toni-Antonova** [comment]
Found the potential problem spot. I edited the 'output' list comprehension in get_activations() and submitted a pull request for you to see.

**Comment by philipperemy** [comment]
@Toni-Antonova Thanks a lot! I've just updated the code. It now works! Thanks for the PR! 72adef26a1836504de84da16f48aeb46ab9ba09b
