### ISSUE TITLE
 SINGLE_ATTENTION_VECTOR = false

### ISSUE THREAD

**Issue by xu-song** [philipperemy/keras-attention-mechanism#12]
Do you have some reference paper, about  **SINGLE_ATTENTION_VECTOR = false** ?

As far as I know, most of papers will set SINGLE_ATTENTION_VECTOR = true.

**Comment by jageshmaharjan** [comment]
+1

**Comment by Dongzhixiao** [comment]
I have the same question. I want to know how to draw the attention results with map picture at the same time.

**Comment by philipperemy** [comment]
I removed this code as it is now deprecated. I updated the code reflecting https://github.com/philipperemy/keras-attention-mechanism/issues/14.
