### ISSUE TITLE
Many to many sequence generation

### ISSUE THREAD

**Issue by jasujaayush** [philipperemy/keras-attention-mechanism#13]
Can you give an example of how to use this for many to many sequence generation with different input and output lengths (greater than 1)? For example, if we have input of 10 timesteps say [1,2,3,4,5,6,7,8,9,10] and we want to generate output [1,10].

**Comment by tessavdheiden** [comment]
Hi, you can use TimeDistributed. Please let me know if you want more info/sample code!

**Comment by joyjitchatterjee** [comment]
@tessavdheiden it would be wonderful if you can give a sample code to use LSTM with attention for many to many sequence generation. Right now, my input sequence is of dimensions (17113,1972) and output sequence of (17113,26). The input sequence is a having 17113 time steps, with 1972 features, and the output is a bag of 26 words for 17113 time steps. Thanks.

**Comment by luoshao23** [comment]
@tessavdheiden It would be nice if you post a sample code. Thanks.

**Comment by philipperemy** [comment]
I advise you to use this one for seq2seq attention: https://github.com/farizrahman4u/seq2seq
