### ISSUE TITLE
这个是CNN版本的attention吗？

### ISSUE THREAD

**Issue by Mariobai** [philipperemy/keras-attention-mechanism#15]
这个是keras实现的CNN加上attention的代码吗？

**Comment by liufei11111** [comment]
My friend.... It is more of LSTM..... And you shouldn't expect that anyone other than me to respond. People don't understand Chinese...

**Comment by alyato** [comment]
@liufei11111 
Are there any attention code of keras for CNN.
Thanks.

**Comment by yushuinanrong** [comment]
@Mariobai 
Attention usually works with RNN for time-series data. This implementation is not for CNN. 
BTW, it's quite interesting to see people post their comments in Chinese. I recommend you not doing this anymore. You won't expect people like me and @liufei11111 understanding Chinese and be willing to answer your question every time.

**Comment by philipperemy** [comment]
@alyato 
- https://github.com/epfml/attention-cnn
- https://arxiv.org/abs/1904.09925
