### ISSUE TITLE
bucketing problem

### ISSUE THREAD

**Issue by LeZhengThu** [philipperemy/keras-attention-mechanism#16]
My sequences have varying lengths and I’m using bucketing to solve the issue. Therefore I define the LSTM input shape as (None, None, features), i.e. there are no explicit timesteps. I wonder if the code can fit my input? Thanks.

**Comment by kwaaksnavel** [comment]
Did you eventually manage to solve the issue? I've run into the same problem...

**Comment by philipperemy** [comment]
You have to either:
- pad the sequences with 0 or mean or any other values.
- set a batch size of 1
- bucketize the sequences together (all sequences with length 2 go together.. and so forth.
