### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sunxx772** [philipperemy/keras-attention-mechanism#17]
Dear sir: when I run python attention_dense.py ,the following errors show:

----- activations -----
Traceback (most recent call last):
  File "attention_dense.py", line 39, in <module>
    attention_vector = get_activations(m, testing_inputs_1, print_shape_only=True)[1].flatten()
IndexError: list index out of range

would you please help me ?thank you very much!

**Comment by philipperemy** [comment]
I removed this code as it is now deprecated. I updated the code reflecting https://github.com/philipperemy/keras-attention-mechanism/issues/14.
