### ISSUE TITLE
Attention Visualization

### ISSUE THREAD

**Issue by alecKarfonta** [philipperemy/keras-attention-mechanism#20]
In the final visualization of the attention weights it says this is showing the attention over input dimensions but the x axis goes to the length of the time steps. So it is showing how important the time step is and not each feature. Shouldn't it be the other way? Where each x is a feature? 

When I apply this to my own dataset it just says the most recent time steps are the most important.

**Comment by philipperemy** [comment]
The attention mechanism was changed (cf. https://github.com/philipperemy/keras-attention-mechanism/issues/14). Issue is outdated.
