### ISSUE TITLE
What is the logic behind the attention layer?

### ISSUE THREAD

**Issue by ajayaadhikari** [philipperemy/keras-attention-mechanism#32]
Ik would like to understand intuitively or theoretically, how the attention layer reflects the attention of the model for a prediction?
Because it is easy for the model to give equal weight for each input feature in the attention layer, and that defeats the purpose of the attention layer.

**Comment by philipperemy** [comment]
Original implementation was bugged. I replaced it with another implementation based on this conversation thread: https://github.com/philipperemy/keras-attention-mechanism/issues/14
