### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by yerzhik** [philipperemy/keras-attention-mechanism#34]
> output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul')
At this line error happens:

output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul')
TypeError: 'module' object is not callable

Not sure what is wrong. Could you help to resolve?

**Comment by kimsjpk1** [comment]
output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul') to change multiply([inputs, a_probs], name='attention_mul')

**Comment by kimsjpk1** [comment]
from keras.layers import multiply

**Comment by philipperemy** [comment]
It was solved in this PR: https://github.com/philipperemy/keras-attention-mechanism/pull/27.
However, I updated the code regarding the comments in https://github.com/philipperemy/keras-attention-mechanism/issues/14.
Problem should be fixed :)
