### ISSUE TITLE
what is the meaning of the second parameter in dot([], [1, 1], name='context_vector')

### ISSUE THREAD

**Issue by Hessen525** [philipperemy/keras-attention-mechanism#37]
Hi, Thanks for your awesome work. 
I have a confusion about the code: context_vector = dot([hidden_states, attention_weights], [1, 1], name='context_vector')
What is the meaning of the second parameter?

**Comment by philipperemy** [comment]
Hey! Thank you! It means a lot to me. There's an explanation in this thread: https://github.com/philipperemy/keras-attention-mechanism/issues/14
I plan to add a good and more exhaustive explanation to the README soon!

**Comment by Hessen525** [comment]
No idea yet, is it that for permute? permute(1,1)?

**Comment by philipperemy** [comment]
@felixhao28 maybe you can answer that one.

**Comment by felixhao28** [comment]
The second argument is the axes to perform dot product. In this case it is equivalent to hidden_states * transpose(attention_weights)
