### ISSUE TITLE
where is dense attention implementation ？

### ISSUE THREAD

**Issue by WAng91An** [philipperemy/keras-attention-mechanism#38]

**Comment by philipperemy** [comment]
It has been removed. We moved to the new attention mechanism described in https://github.com/philipperemy/keras-attention-mechanism/issues/14.

If you still want the older code though, you can find it here: https://github.com/philipperemy/keras-attention-mechanism/blob/5a07135bddd2511d681fb3280ab02ee103e3efb3/attention_dense.py#L16
