### ISSUE TITLE
ask a problem about your code

### ISSUE THREAD

**Issue by yangdongchao** [philipperemy/keras-attention-mechanism#39]
in your code ,you want to pay more attention on the 10th step. your Experimental results also prove it.
But, your code seems not foucs on the 10th step. please read following code.
` score_first_part = Dense(hidden_size, use_bias=False, name='attention_score_vec')(hidden_states) 
    #            score_first_part           dot        last_hidden_state     => attention_weights
    # (batch_size, time_steps, hidden_size) dot   (batch_size, hidden_size)  => (batch_size, time_steps)
    h_t = Lambda(lambda x: x[:, -1, :], output_shape=(hidden_size,), name='last_hidden_state')(hidden_states)
    score = dot([score_first_part, h_t], [2, 1], name='attention_score') `

the way you calculate ‘score’ is  score_first_part dot h_t. 
the way you get h_t  :  h_t = Lambda(lambda x: x[:, -1, :], output_shape=(hidden_size,), name='last_hidden_state') .  in my view 'lambda x: x[:, -1, :]' means you choose the last step in the time sequence , in other word, you pay more attention on the 20th step.(in your  code you define TIME_STEPS = 20). 
so, if my understanding is right, you should change you code to be   h_t = Lambda(lambda x: x[:, 9, :], output_shape=(hidden_size,), name='last_hidden_state') . 
of course, my understanding perhaps wrong. i am lookingforward your reply . 
thank you.

**Comment by philipperemy** [comment]
@yangdongchao source code got updated This previous implementation was buggy.
