### ISSUE TITLE
attention implementation help for OCR

### ISSUE THREAD

**Issue by shekarneo** [philipperemy/keras-attention-mechanism#41]
Hi,

how can i add the attention model fot keras image_ocr implementation

**Comment by philipperemy** [comment]
I don't think it's a good idea to link it to any Image OCR implementation.

I'd say, this module is better suited for time series and NLP data.

You should probably look for CAM (Class Activation Maps) and Saliency Maps:
- https://paperswithcode.com/method/cam
- https://debuggercafe.com/saliency-maps-in-convolutional-neural-networks/

Let me know if you need more help on that!

**Comment by shekarneo** [comment]
@philipperemy  Thanks
