### ISSUE TITLE
Hiddent state parameter, what really should be passed? 

### ISSUE THREAD

**Issue by mohamedScikitLearn** [philipperemy/keras-attention-mechanism#44]
Hi, thanks for the implementation!
I have been trying to implement this code
`model = Sequential() 
model.add(Embedding(300000, 100, input_length=250))
model.add(LSTM(units=250, return_sequences=True, dropout=0.1, recurrent_dropout=0.2))
model.add(attention_3d_block( )) 
model.add(Flatten())
 model.add(Dense(200, activation='relu'))
model.add(Dense(3, activation='softmax'))`

**Error**  `TypeError: attention_3d_block() missing 1 required positional argument: 'hidden_states'
`
I tried to explore the given documentation but I couldn't understand what really should be passed there.

**Comment by philipperemy** [comment]
Hi! Yep at the moment, this attention_3d_block is not a keras.layer yet. You can't technically apply Sequential here. Refer to this: https://github.com/philipperemy/keras-attention-mechanism/blob/0309dbf79da32c0d8d90925660fc4cc7fe53dc8a/examples/example-attention.py#L63 to know how to do it.
It's in the backlog to make it as keras.layer.
If you have any other questions, feel free to re-open this ticket.
Thanks.
