### ISSUE TITLE
pip install and numpy, keras packages are forced to be uninstalled

### ISSUE THREAD

**Issue by waner1211** [philipperemy/keras-attention-mechanism#45]
Hi,

As I install the keras-attention-mechanism to my conda3 by pip, the essential packages of numpy and keras are unexpectedly being uninstalled. Do you know why? 

Bests,
Peiwan

**Comment by philipperemy** [comment]
Hi,
it looks very stranger. The setup.py will install numpy and keras but it will never uninstall them.
https://github.com/philipperemy/keras-attention-mechanism/blob/0309dbf79da32c0d8d90925660fc4cc7fe53dc8a/setup.py#L13
