### ISSUE TITLE
Use this repository for CNN 

### ISSUE THREAD

**Issue by sepehrgolriz** [philipperemy/keras-attention-mechanism#46]
Dear Sir,

Would it be possible to use this repo for CNN network also?

Thanks and regards.

**Comment by philipperemy** [comment]
@sepehrgolriz I haven't thought about it but I think it's possible to combine CNN+LSTM.
But in your case, I advise you to look into GradCam for CNN: https://towardsdatascience.com/demystifying-convolutional-neural-networks-using-gradcam-554a85dd4e48.
Just a search on Google "GradCam CNN" should help you here.
Thanks
