### ISSUE TITLE
attention_lstm.py does not work for Theano backend

### ISSUE THREAD

**Issue by Love-world** [philipperemy/keras-attention-mechanism#5]
When I run the script attention_lstm.py, there is a problem in the line 17. Just like the following problem:
"input_dim=int(inputs.shape[2])"
"TypeError: int() argument must be a string or a number, not 'TensorVariable'"

**Comment by philipperemy** [comment]
@Love-world do you use the Tensorflow backend?

**Comment by Love-world** [comment]
Yes, I use the Theano backend.
It works with the Tensorflow backend.
Thank you very much.

**Comment by sun-peach** [comment]
Hi, dear all,

Even though I changed to Tensorflow backend, I still have issue:
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/fei.t/Tools/attention-model/attention_lstm.py", line 59, in <module>
    m = model_attention_applied_before_lstm()
  File "/home/fei.t/Tools/attention-model/attention_lstm.py", line 42, in model_attention_applied_before_lstm
    attention_mul = attention_3d_block(inputs)
  File "/home/fei.t/Tools/attention-model/attention_lstm.py", line 20, in attention_3d_block
    a = Dense(TIME_STEPS, activation='softmax')(a)
  File "/home/fei.t/anaconda2/envs/fei/lib/python2.7/site-packages/keras/engine/topology.py", line 470, in __call__
    self.assert_input_compatibility(x)
  File "/home/fei.t/anaconda2/envs/fei/lib/python2.7/site-packages/keras/engine/topology.py", line 411, in assert_input_compatibility
    str(K.ndim(x)))
Exception: Input 0 is incompatible with layer dense_1: expected ndim=2, found ndim=3

Does anyone know how to fix this? Thank you.

**Comment by philipperemy** [comment]
```
[10:15:25 - 17-06-24] /Users/philipperemy % python3
Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.0.2'
>>> import tensorflow
>>> tensorflow.__version__
'1.2.0'
```

what do you have?

**Comment by sun-peach** [comment]
same version, but I use python 2.7

**Comment by philipperemy** [comment]
When you said same version, do you mean you have both Keras 2.0.2 and Tensorfow 1.2.0?

**Comment by philipperemy** [comment]
Can you print the full output when you run the script too. Thanks

**Comment by sun-peach** [comment]
Hi, Philip,

It seems my tensorflow has low version 1.0.0. I think this is the problem. Thank you.

**Comment by philipperemy** [comment]
Ok great!
