### ISSUE TITLE
get_config

### ISSUE THREAD

**Issue by edithangelicar** [philipperemy/keras-attention-mechanism#51]
Hi,
Perhaps do you have another implementation with the get_config function for saving the model in keras? I had been trying but I always get this error: 
raise ValueError('A `Dot` layer should be called '

ValueError: A `Dot` layer should be called on a list of 2 inputs.

Thanks!

**Comment by philipperemy** [comment]
Which version of tensorflow are you using? Update your tensorflow.

**Comment by edithangelicar** [comment]
I have tensorflow  2.3.0. 

For example, at the end of your example (example-attention.py ) after "model.fit"  I wrote:

 model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=max_epoch,
              batch_size=64, callbacks=[VisualiseAttentionMap()])

#What I wrote
model.save('test_model.h5') 
modelh5 = load_model('test_model.h5',  custom_objects={'Attention': Attention})

Error I get: 

  File "C:\Users\edith\anaconda3\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 663, in build
    raise ValueError('A `Dot` layer should be called '

ValueError: A `Dot` layer should be called on a list of 2 inputs.


I am attaching a picture of the script where I try to save and load the model
![save_error](https://user-images.githubusercontent.com/46884145/98462981-62c97100-21b8-11eb-9e57-4508113f64d4.png)


Thank you very much for your help and time!

**Comment by philipperemy** [comment]
Good catch I think we need to use `Dot` instead of `dot`.

**Comment by philipperemy** [comment]
Hum still does not work and not sure why:

![Uploading image.png…]()

**Comment by philipperemy** [comment]
@edithangelicar `save` can sometimes be very tricky. I advise you to use `load_weights` and `save_weights` instead:

You will have to re-define your model and instanciate your model beforehand but I don't see any other solutions in the short term.

```python
model.save_weights('test_model.h5')
modelh5 = model.load_weights('test_model.h5')
```

**Comment by edithangelicar** [comment]
Thank you for checking and for your help! 
If at some point you get to know how to solve the problem, please let me know. 
Thank you!

**Comment by edithangelicar** [comment]
I think I managed, you have to change your model from sequential to functional API. Thank you!

**Comment by nickion** [comment]
Have literally just hit this issue myself; thanks for the comments and update.

**Comment by edithangelicar** [comment]
Nickion, also remember to create the get_config and from_config in the class: https://keras.io/guides/serialization_and_saving/

**Comment by philipperemy** [comment]
Great @edithangelicar can you provide a small snippet to show how to get it to work?

**Comment by edithangelicar** [comment]
yes. here are some pictures, it is lightly modified for fitting  what I am doing so it doesn't correspond exactly to your example.
![attention_class](https://user-images.githubusercontent.com/46884145/98571392-cd5fd700-22b4-11eb-9c44-e2cfa393184d.png)
![lstm_api](https://user-images.githubusercontent.com/46884145/98571396-cdf86d80-22b4-11eb-9ac0-73f79d6d1ebd.png)

**Comment by philipperemy** [comment]
@edithangelicar can you paste it here instead of pictures? It will be easier for others to understand it.

**Comment by edithangelicar** [comment]
I am attaching txt since here I can't paste python files

[functional_lstm.txt](https://github.com/philipperemy/keras-attention-mechanism/files/5515692/functional_lstm.txt)
[attention.txt](https://github.com/philipperemy/keras-attention-mechanism/files/5515694/attention.txt)

**Comment by philipperemy** [comment]
Alright thanks!
