### ISSUE TITLE
Add guidance to README to use Functional API for saving models that use this layer

### ISSUE THREAD

**Issue by bendykstra94** [philipperemy/keras-attention-mechanism#55]
Hi there!

Thanks so much for implementing this and all of the other work that you do!

I ran in to an issue with loading a model uses this the Attention layer in a sequential model. However, the Attention layer is defined using the Function API and Keras does not like it when you try to load a mixed model. 

Specifically, my error was 

```
m = keras.models.load_model('saved_mixed_model_path',
            custom_objects = { 'Attention': Attention}
           )

=> ValueError: A merge layer should be called on a list of inputs.

```

To solve this, I had to convert my model to one that uses the functional API and retrain.

Part of my confusion stems from the examples where both the Sequential and Functional APIs are used. In [this example](https://github.com/philipperemy/keras-attention-mechanism/blob/master/examples/example-attention.py) you successfully save and load a model using only Functional API. But in [this lstm example](https://github.com/philipperemy/keras-attention-mechanism/blob/master/examples/find_max.py) the Sequential API is used and no loading/saving is done.

Could a caveat be added to the README.md saying that if you plan to load/save these models, only the Functional API should be used when building the model that uses the Attention layer?

Cheers

**Comment by bendykstra94** [comment]
Related https://github.com/philipperemy/keras-attention-mechanism/issues/51

**Comment by philipperemy** [comment]
@bendykstra94 sorry for the late reply! First of all, thanks very much! I updated the code. Can you check if the issue still persists? Best :)

**Comment by bendykstra94** [comment]
@philipperemy Thanks! Examples look good now.

**Comment by philipperemy** [comment]
Good to hear
