### ISSUE TITLE
what do the h_t mean in the Attention model?

### ISSUE THREAD

**Issue by fwyc0573** [philipperemy/keras-attention-mechanism#57]
Hi there!
Thanks so much for implementing this and all of the other work that you do!
I wanna know the meaning of h_t，i.e h_t = Lambda(lambda x: x[:, -1, :], output_shape=(hidden_size,), name='last_hidden_state')(hidden_states) . Well, in Luong's paper the h_t was used as the input the hidden state. But how to explain it in a scene which is not seq2seq?

**Comment by philipperemy** [comment]
@fwyc0573 try to refer to this issue: https://github.com/philipperemy/keras-attention-mechanism/issues/14.

Most of it is explained in here ;)
