### ISSUE TITLE
Please update version

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [philipperemy/keras-attention-mechanism#62]
Running `pip install attention` installs version 3 (Sep 2020) but there have been updates since.  Currently I cannot specify the # of units without receiving an error:

> TypeError: __init__() takes 1 positional argument but 2 were given

The traceback shows an init method that does not handle the `units` parameter (old code).

**Comment by philipperemy** [comment]
@JakeTheSnake3p0 thanks for reporting! I updated the version to 4.1.
