### ISSUE TITLE
TypeError: __call__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by sxk000** [philipperemy/keras-attention-mechanism#64]
when i use the code，got TypeError: __call__() takes 2 positional arguments but 3 were given

whta is the problem？ how to fix it ？

thinks

**Comment by philipperemy** [comment]
@sxk000 can you be a bit more precise? Thanks.

**Comment by philipperemy** [comment]
Closing this issue as it lacks of clarity.
